view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # éœ€è¦ç™»å½•æ‰èƒ½é˜…è¯»çš„æ–‡ç« é˜…è¯»æ¬¡æ•°
    zsxqArticleReadCount: 20 # çŸ¥è¯†æ˜Ÿçƒç”¨æˆ·æ‰èƒ½é˜…è¯»çš„æ–‡ç« é˜…è¯»æ¬¡æ•°ç»Ÿè®¡é—´éš”ï¼Œå•ä½ï¼šåˆ†é’Ÿ
    needPayArticleReadCount: 20 # ä»˜è´¹æ–‡ç« ï¼Œæœªä»˜è´¹å¯ä»¥çœ‹åˆ°çš„æ–‡ç« å†…å®¹
    websiteName: æŠ€æœ¯æ´¾
    websiteLogoUrl: https://paicoding.com/img/icon.png
    websiteFaviconIconUrl: https://paicoding.com/img/icon.png
    zsxqUrl: https://paicoding.com/article/detail/314
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: è”ç³»æˆ‘ - æ²‰é»˜ç‹äºŒçš„ç‹—è…¿å­
    contactMeWxQrCode: https://cdn.tobebetterjavaer.com/paicoding/paicoding-qrcode.png  # è¿™é‡Œæ˜¯ç”¨äºç™»å½•çš„æ™®é€šå…¬ä¼—å·çš„äºŒç»´ç 
    contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: å¤‡æ¡ˆè¢«å°äººå·è¢­äº†
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: æ¬¢è¿æ¥åˆ°æŠ€æœ¯æ´¾ï¼Œæˆ³<a href="/article/detail/15">æŠ€æœ¯æ´¾å…¨æ–¹ä½è§†è§’è§£è¯»</a>äº†è§£æˆ‘ä»¬
    columnInfoNews: ğŸ‰ æ¬¢è¿æ¥åˆ°æŠ€æœ¯æ´¾æ•™ç¨‹é¢‘é“ï¼è¿™é‡Œæ±‡é›†äº†ä¼˜è´¨çš„æŠ€æœ¯ä¸“æ å†…å®¹ï¼ŒåŠ©ä½ å¿«é€Ÿæˆé•¿ï¼
    oss: